/** Shared food/non-food keyword sets used to filter image search results. */
export const NON_FOOD_KEYWORDS = new Set([
  "logo", "icon", "flag", "map", "coat of arms", "emblem", "seal", "stamp", "coin", "banknote",
  "medal", "badge", "building", "house", "church", "temple", "mosque", "synagogue", "monument",
  "statue", "fountain", "bridge", "tower", "castle", "car", "bus", "train", "airplane", "ship",
  "boat", "bicycle", "mountain", "hill", "valley", "river", "lake", "ocean", "sea", "forest",
  "desert", "island", "beach", "waterfall", "animal", "bird", "insect", "reptile", "mammal",
  "dog", "cat", "horse", "cow", "pig", "sheep", "goat", "flower", "tree", "plant", "mushroom",
  "algae", "person", "people", "man", "woman", "child", "baby", "face", "portrait", "singer",
  "actor", "politician", "athlete", "player", "painting", "drawing", "sketch", "illustration",
  "diagram", "chart", "graph", "plot", "table", "formula", "screenshot", "capture", "screen",
  "interface", "button", "texture", "pattern", "background", "wallpaper", "abstract", "geometric",
  "minimalist", "modern", "landscape", "skyline", "panorama", "aerial", "sport", "game", "match",
  "tournament", "competition", "music", "concert", "festival", "performance", "movie", "film",
  "cinema", "theater", "opera", "book", "magazine", "newspaper", "journal", "computer", "phone",
  "tablet", "laptop", "monitor", "clothing", "dress", "shirt", "shoes", "hat", "furniture",
  "chair", "table", "bed", "sofa", "weapon", "sword", "gun", "bomb", "tank", "tool", "hammer",
  "saw", "drill", "wrench", "medical", "hospital", "doctor", "nurse", "medicine", "military",
  "army", "navy", "air force", "soldier", "breed", "species", "genus", "fossil", "evolution",
  "extinct", "endangered", "habitat", "wild", "packaging", "brand", "label", "nutrition",
  "costume", "craft", "diy", "decoration", "decor", "tattoo", "sticker", "emoji", "outfit",
  "fashion", "style", "makeup", "stock photo", "selfie", "headshot", "profile", "farm", "farming",
  "agriculture", "livestock", "poultry", "pet", "zoo", "cage", "enclosure", "aquarium", "natural",
  "nature", "environment", "ecosystem", "puppy", "kitten", "cub", "foal", "sports", "football",
  "soccer", "basketball", "baseball", "tennis", "golf", "rugby", "cricket", "hockey", "racing",
  "race", "runner", "cycling", "swimming", "skiing", "snowboarding", "surfing", "skateboarding",
  "climbing", "hiking", "fishing", "hunting", "camping", "yoga", "fitness", "gym", "workout",
  "exercise", "dance", "ballet", "wedding", "party", "celebration", "birthday", "graduation",
  "ceremony", "parade", "protest", "conference", "meeting", "classroom", "school", "university",
  "college", "office", "factory", "warehouse", "construction", "road", "street", "highway",
  "traffic", "city", "town", "village", "neighborhood", "park", "garden", "zoo", "museum",
  "library", "store", "shop", "mall", "market", "restaurant exterior", "restaurant interior",
  "bar interior", "cafe interior", "kitchen", "chef portrait", "logo design", "brand logo",
]);

export const FOOD_KEYWORDS = [
  "food", "cuisine", "dish", "meal", "recipe", "ingredient", "cooking", "baking", "grill",
  "roast", "steam", "fry", "saute", "boil", "broil", "bake", "fresh", "organic", "homemade",
  "gourmet", "delicious", "tasty", "flavorful", "savory", "sweet", "spicy", "healthy",
  "plate", "platter", "bowl", "serving", "portion", "dinner", "lunch", "breakfast", "brunch",
  "appetizer", "entree", "main course", "dessert", "side dish", "salad", "soup", "sandwich",
  "pizza", "pasta", "burger", "steak", "seafood", "chicken", "vegetarian", "vegan",
  "restaurant", "menu", "chef", "kitchen", "culinary", "gastronomy", "fusion",
  "traditional", "authentic", "regional", "local", "artisan", "handcrafted",
];

export const FOOD_PATTERNS = [
  /\b(food|dish|cuisine|meal|plate)\b/i,
  /\b(recipe|cooking|baking|grilling|roasting)\b/i,
  /\b(ingredient|fresh|organic|gourmet|homemade)\b/i,
  /\b(dinner|lunch|breakfast|brunch|appetizer|entree|dessert)\b/i,
  /\b(restaurant|chef|kitchen|culinary|menu)\b/i,
  /\b(pizza|pasta|burger|steak|seafood|chicken|salad|soup|sandwich)\b/i,
  /\b(delicious|tasty|flavorful|savory|sweet|spicy)\b/i,
];
